In [45]:
# Criando Matrizes

import numpy as np

# A partir do np.array()
matriz_1 = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]])
print(matriz_1)
print()
# Outra forma
matriz_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Criando matrizes: zeros, uns, valor fixo
print("Matriz zeros:")
matriz_zeros = np.zeros((3, 3))
print(matriz_zeros)
print()
print("Matriz uns:")
matriz_ones = np.ones((3, 3))
print(matriz_ones)
print()
print("Matriz com valor fixo:")
matriz_fixa = np.full((3, 3), 5)
print(matriz_fixa)

Matriz zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matriz uns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matriz com valor fixo:
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [20]:
# Criando matrizes: Matriz identidade
print("Matriz identidade:")
matriz_identidade = np.eye(4)
print(matriz_identidade)

Matriz identidade:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
# Criando matrizes: valores aleatórios entre 0 e 1 e valores aleatórios em um intervalo
print("Matriz de valores aleatórios entre 0 e 1:")
matriz_aleatoria = np.random.rand(3, 3)
print(matriz_aleatoria.round(2))
print()
print("Matriz de valores aleatórios entre 10 e 20:")
matriz_aleatoria_intervalo = np.random.uniform(10, 20, (3, 3))
print(matriz_aleatoria_intervalo.round(2))


Matriz de valores aleatórios entre 0 e 1:
[[0.24 0.42 0.76]
 [0.37 0.4  0.96]
 [0.77 0.12 0.66]]

Matriz de valores aleatórios entre 10 e 20:
[[15.4  11.39 10.3 ]
 [15.28 15.67 19.04]
 [17.74 12.98 13.28]]


In [27]:
# Atributos da Matriz
print(matriz_1)
print()
print("Atributos da matriz:")
print("Número de dimensões:", matriz_1.ndim)
print("Forma (número de linhas e colunas):", matriz_1.shape)
print("Número total de elementos:", matriz_1.size)
print("Tipo de dados dos elementos:", matriz_1.dtype)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

Atributos da matriz:
Número de dimensões: 2
Forma (número de linhas e colunas): (3, 3)
Número total de elementos: 9
Tipo de dados dos elementos: int64


In [39]:
# RESHAPE() E FLATTEN() - Mudando a forma da matriz
sequencia = np.arange(1, 10)
print("Sequência original: \n", sequencia)
print()
print("Sequência reshapeada para 3x3: \n", sequencia.reshape(3, 3))
print()
print("Sequência reshapeada para 1 linha e 9 colunas: \n", sequencia.reshape(1, 9))
print()
print("Sequência reshapeada para 9 linhas e 1 coluna: \n", sequencia.reshape(9, 1))
print()
print("Sequência flattenada para 1 dimensão: \n", sequencia.flatten())

Sequência original: 
 [1 2 3 4 5 6 7 8 9]

Sequência reshapeada para 3x3: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sequência reshapeada para 1 linha e 9 colunas: 
 [[1 2 3 4 5 6 7 8 9]]

Sequência reshapeada para 9 linhas e 1 coluna: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

Sequência flattenada para 1 dimensão: 
 [1 2 3 4 5 6 7 8 9]


### Exercício 1 — Fácil: Criando e inspecionando matrizes

**Enunciado:** Crie as seguintes matrizes e exiba o `shape`, `ndim` e `size` de cada uma:

a) Uma matriz 3×3 com os valores de 1 a 9 (use `arange` + `reshape`).  
b) Uma matriz de zeros com 4 linhas e 2 colunas.  
c) A matriz identidade de tamanho 3.

In [42]:
import numpy as np

# Uma matriz 3x3 com valore de 1 a 9
matriz_3x3 = np.arange(1, 10)

print(matriz_3x3.reshape(3,3))
print("shape:", matriz_3x3.shape)
print("ndim:", matriz_3x3.ndim)
print("size:", matriz_3x3.size)
print()

# Uma matriz de zeros com 4 linhas e 2 colunas
matriz_zeros = np.zeros((4,2))
print(matriz_zeros)
print("shape:", matriz_zeros.shape)
print("ndim:", matriz_zeros.ndim)
print("size:", matriz_zeros.size)
print()

#A matriz identidade de tamanho 3
matriz_ident = np.eye(3)
print(matriz_ident)
print("shape:", matriz_ident.shape)
print("ndim:", matriz_ident.ndim)
print("size:", matriz_ident.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (9,)
ndim: 1
size: 9

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
shape: (4, 2)
ndim: 2
size: 8

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
shape: (3, 3)
ndim: 2
size: 9


In [50]:
# Indexação e Fatiamento de Matrizes
print(matriz_1)
#Elemento na linha 0, coluna 1
print("Elemento na linha 0, coluna 1:", matriz_1[0, 1])
# Linha 2 inteira
print("Linha 2 inteira:", matriz_1[2, :])
# Coluna 0 inteira
print("Coluna 0 inteira:", matriz_1[:, 0])
# Submatriz das linhas 0 e 1, colunas 1 e 2
print("Submatriz das linhas 0 e 1, colunas 1 e 2:\n", matriz_1[0:2, 1:3])
# última linha e última coluna
print("Última linha e última coluna:", matriz_1[-1, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento na linha 0, coluna 1: 2
Linha 2 inteira: [7 8 9]
Coluna 0 inteira: [1 4 7]
Submatriz das linhas 0 e 1, colunas 1 e 2:
 [[2 3]
 [5 6]]
Última linha e última coluna: 9


### Exercício 2 — Fácil: Indexação e fatiamento

**Enunciado:** Dada a matriz de temperaturas diárias de 3 cidades ao longo de 5 dias:

```python
temperaturas = np.array([
    [32, 33, 31, 29, 35],   # Cidade A
    [28, 27, 30, 26, 29],   # Cidade B
    [22, 24, 21, 23, 25]    # Cidade C
])
```

Extraia:
- A temperatura da Cidade B no 3º dia (índice 2).
- Todas as temperaturas da Cidade C.
- As temperaturas de todas as cidades no último dia.
- A submatriz das cidades A e B nos primeiros 3 dias.


In [51]:
temperaturas = np.array([
    [32, 33, 31, 29, 35],   # Cidade A : temp1, temp2, temp3, temp4, temp5
    [28, 27, 30, 26, 29],   # Cidade B
    [22, 24, 21, 23, 25]    # Cidade C
])

# A temperatura da Cidade B no 3º dia (índice 2)
print(temperaturas[1, 2])
print()

# Todas as temperaturas da Cidade C
print(temperaturas[2, :])
print()
# As temperaturas de todas as cidades no último dia
print(temperaturas[:, -1])
print()
# A submatriz das cidades A e B nos primeiros 3 dias
submatriz_temp = temperaturas[0:2, 0:3]
print(submatriz_temp)

30

[22 24 21 23 25]

[35 29 25]

[[32 33 31]
 [28 27 30]]


In [62]:
# Operações
# A + B             # element-wise: soma posição a posição
# A * B             # element-wise: multiplica posição a posição (NÃO é produto matricial!)
# np.dot(A, B)      # produto matricial (matemática de verdade)
# A @ B             # mesmo que np.dot — sintaxe mais moderna
# A.T               # transposta: troca linhas por colunas

# Estatística por Eixo
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.sum(m, axis=0)    # soma por coluna (colapsa as linhas)
np.sum(m, axis=1)    # soma por linha (colapsa as colunas)
np.mean(m, axis=1)   # média de cada linha

# Observação n.clip() - limitar os valores de uma matriz a um intervalo específico
n = np.array([1, 5, 10, 15, 20])
n_clipada = n.clip(3, 12)
print(n_clipada)
print()
# Broadcasting - operações entre matrizes de formas diferentes
quantidades = np.array([
    [120, 340],
    [80, 150]
])
precos = np.array([
    [29.90, 49.90]
])

# Para multiplicar cada LINHA pelo preço do seu produto:
print(precos.reshape(-1, 1))  # Transforma a linha em coluna para o broadcast funcionar
receitas = quantidades * precos.reshape(-1, 1)    # (2,1) faz broadcast correto

print(receitas)




[ 3  5 10 12 12]

[[29.9]
 [49.9]]
[[ 3588. 10166.]
 [ 3992.  7485.]]


### Exercício 3 — Médio: Reshape, flatten e estatísticas por eixo

**Enunciado:** Você tem as vendas mensais de uma loja ao longo de um ano, registradas em um array 1D de 12 elementos (Janeiro a Dezembro):

```python
vendas_ano = np.array([45, 52, 48, 60, 55, 70, 80, 78, 65, 58, 50, 90])
```

1. Reorganize esse array em uma matriz `(4, 3)` onde cada linha representa um trimestre e cada coluna representa um mês dentro do trimestre.
2. Calcule o total de vendas por trimestre (soma por linha — `axis=1`).
3. Calcule a média de vendas por mês dentro de cada trimestre (já feito pelo item 2 se dividir por 3).
4. Identifique o trimestre com maior faturamento.
5. Use `flatten()` para recuperar o array original.

In [80]:
# 1. Reorganize esse array em uma matriz `(4, 3)` onde cada linha representa
# um trimestre e cada coluna representa um mês dentro do trimestre.
vendas_ano = np.array([45, 52, 48, 60, 55, 70, 80, 78, 65, 58, 50, 90])
vendas_ano_4x3 = vendas_ano.reshape(4, 3)
print(vendas_ano.reshape(4,3))
print()
# 2. Calcule o total de vendas por trimestre (soma por linha — `axis=1`).
total_vendas_trimestre = vendas_ano_4x3.sum(axis = 1)
print("2. Total de vendas por trimestre: \n", total_vendas_trimestre)
print()
# 3. Calcule a média de vendas por mês dentro de cada trimestre (já feito pelo item 2 se dividir por 3).
media_vendas_mes_trimestre = total_vendas_trimestre / 3
print("3. Média de vendas por mês dentro de cada trimestre: \n", 
      media_vendas_mes_trimestre.round(2))
print("Ou:")
media_vendas_mes_trimestre_2 = vendas_ano_4x3.mean(axis = 1)
print("3. Média de vendas por mês dentro de cada trimestre (usando mean): \n", 
      media_vendas_mes_trimestre_2.round(2))
print()
# 4. Identifique o trimestre com maior faturamento.
trimestre_maior_faturamento = np.argmax(total_vendas_trimestre) + 1  # +1 para ajustar índice
print("4. Trimestre com maior faturamento: \n Trimestre", trimestre_maior_faturamento)
print()
# 5. Use `flatten()` para recuperar o array original.
print("5. Depois do flatten: \n", vendas_ano.flatten())

[[45 52 48]
 [60 55 70]
 [80 78 65]
 [58 50 90]]

2. Total de vendas por trimestre: 
 [145 185 223 198]

3. Média de vendas por mês dentro de cada trimestre: 
 [48.33 61.67 74.33 66.  ]
Ou:
3. Média de vendas por mês dentro de cada trimestre (usando mean): 
 [48.33 61.67 74.33 66.  ]

4. Trimestre com maior faturamento: 
 Trimestre 3

5. Depois do flatten: 
 [45 52 48 60 55 70 80 78 65 58 50 90]


### Exercício 4 — Médio: Operações e transposição

**Enunciado:** Uma escola tem as notas de 3 alunos em 4 matérias:

```python
notas = np.array([
    [7.0, 8.5, 6.0, 9.0],   # Aluno 1: Mat, Port, Hist, Cien
    [9.0, 7.5, 8.0, 8.5],   # Aluno 2
    [6.5, 9.0, 7.5, 7.0]    # Aluno 3
])
```

Responda **sem usar laços `for`**:

1. Calcule a média de cada aluno (média por linha).
2. Transpose a matriz e calcule a média de cada matéria (que agora são as linhas).
3. Calcule a diferença entre as notas do Aluno 1 e do Aluno 2 (element-wise).
4. Aplique um bônus de +0.5 em todas as notas (broadcasting). Certifique-se que nenhuma nota ultrapasse 10 usando `np.clip()` — pesquise como funciona!

In [93]:
notas = np.array([
    [7.0, 8.5, 6.0, 9.0],   # Aluno 1: Mat, Port, Hist, Cien
    [9.0, 7.5, 8.0, 8.5],   # Aluno 2
    [6.5, 9.0, 7.5, 7.0]    # Aluno 3
])
print(notas)
print()
# 1. Calcule a média de cada aluno (média por linha).
media_alunos = notas.mean(axis=1)
print("1. Média de cada aluno: \n", media_alunos.round(2))
print()
# 2. Transpose a matriz e calcule a média de cada matéria (que agora são as linhas).
notas_transposta = notas.T
print("Matriz transposta: \n", notas_transposta)
media_materias = notas_transposta.mean(axis=1)
print("2. Média de cada matéria: \n", media_materias.round(2))
print()
# 3. Calcule a diferença entre as notas do Aluno 1 e do Aluno 2 (element-wise).
notas_aluno_1 = notas[0, :]
notas_aluno_2 = notas[1, :]
diferenca_notas = notas_aluno_1 - notas_aluno_2
print("3. Diferença entre as notas do Aluno 1 e do Aluno 2: \n", diferenca_notas.round(2))
print()
# 4. Aplique um bônus de +0.5 em todas as notas (broadcasting). Certifique-se que 
# nenhuma nota ultrapasse 10 usando `np.clip()` — pesquise como funciona!
## sem o clip (tranquilo pois nenhuma passou de 10)
notas_bonus = notas + 0.5
print("4. Notas com bônus (sem clip): \n", notas_bonus.round(2))
## com o clip
notas_bonus_clip = np.clip(notas_bonus, 0, 10)
print("Notas com bônus (com clip): \n", notas_bonus_clip.round(2))

[[7.  8.5 6.  9. ]
 [9.  7.5 8.  8.5]
 [6.5 9.  7.5 7. ]]

1. Média de cada aluno: 
 [7.62 8.25 7.5 ]

Matriz transposta: 
 [[7.  9.  6.5]
 [8.5 7.5 9. ]
 [6.  8.  7.5]
 [9.  8.5 7. ]]
2. Média de cada matéria: 
 [7.5  8.33 7.17 8.17]

3. Diferença entre as notas do Aluno 1 e do Aluno 2: 
 [-2.   1.  -2.   0.5]

4. Notas com bônus (sem clip): 
 [[7.5 9.  6.5 9.5]
 [9.5 8.  8.5 9. ]
 [7.  9.5 8.  7.5]]
Notas com bônus (com clip): 
 [[7.5 9.  6.5 9.5]
 [9.5 8.  8.5 9. ]
 [7.  9.5 8.  7.5]]


### Exercício 5 — Desafio: Mini Análise de Dataset com Matrizes

**Enunciado:** Uma empresa de e-commerce tem os dados de 5 produtos em 4 regiões do Brasil (Norte, Nordeste, Sudeste, Sul), representando as **quantidades vendidas** no mês:

```python
quantidades = np.array([
    [120, 340, 890, 210],   # Produto 1: Norte, Nordeste, Sudeste, Sul
    [ 80, 150, 560, 300],   # Produto 2
    [200, 420, 1100, 480],  # Produto 3
    [ 50,  90,  320, 180],  # Produto 4
    [310, 500, 1450, 620]   # Produto 5
])

precos = np.array([29.90, 49.90, 19.90, 89.90, 14.90])  # Preço de cada produto
```

Resolva **sem usar laços `for`**:

1. Calcule a receita total gerada por cada produto em todas as regiões (soma das colunas de cada linha × preço).
2. ''Calcule o total de unidades vendidas por região (soma de cada coluna).
3. Identifique qual produto e qual região têm o maior e o menor volume de vendas.
4. Crie uma matrix de receitas `(5, 4)` onde cada célula é `quantidade × preço_do_produto` para aquela região. *(Dica: use reshape ou broadcasting 2D.)*
5. Exiba a receita total por região.''

> 💡 **Dica para o item 4:** Tente `quantidades * precos.reshape(5, 1)` — isso multiplica cada linha pelo preço correspondente daquele produto (broadcasting 2D).


In [94]:
import numpy as np

quantidades = np.array([
    [120, 340, 890, 210],   # Produto 1
    [ 80, 150, 560, 300],   # Produto 2
    [200, 420, 1100, 480],  # Produto 3
    [ 50,  90,  320, 180],  # Produto 4
    [310, 500, 1450, 620]   # Produto 5
])

precos = np.array([29.90, 49.90, 19.90, 89.90, 14.90])  # Preço de cada produto

# Calcule a receita total gerada por cada produto em todas as regiões 
# (soma das colunas de cada linha x preço)
receita_total = np.sum(quantidades, axis=1) * precos
print("Receita total por produto: \n", receita_total)
print()

# 2. Calcule o total de unidades vendidas por região (soma de cada coluna).
total_por_regiao = np.sum(quantidades, axis=0)
print("Total de unidades vendidas por região: \n", total_por_regiao)
print()

# 3. Identifique qual produto e qual região têm o maior e o menor volume de vendas.
produto_mais_vendido = np.argmax(np.sum(quantidades, axis=1))
produto_menos_vendido = np.argmin(np.sum(quantidades, axis=1))
regiao_mais_vendida = np.argmax(np.sum(quantidades, axis=0))
regiao_menos_vendida = np.argmin(np.sum(quantidades, axis=0))
print(f"Produto mais vendido: Produto {produto_mais_vendido + 1}")
print(f"Produto menos vendido: Produto {produto_menos_vendido + 1}")
print(f"Região mais vendida: Região {regiao_mais_vendida + 1}")
print(f"Região menos vendida: Região {regiao_menos_vendida + 1}")
print()

# 4. Crie uma matrix de receitas `(5, 4)` onde cada célula é `quantidade × preço_do_produto` para aquela região. 
# #*(Dica: use reshape ou broadcasting 2D.)*
precos = precos.reshape(5,1)
receitas = quantidades * precos
print("Matriz de receitas por produto e região:")
print(receitas)
print()

# 5. Exiba a receita total por região.
receita_por_regiao = np.sum(receitas, axis=0)
print("Receita total por região:", receita_por_regiao)  

Receita total por produto: 
 [46644. 54391. 43780. 57536. 42912.]

Total de unidades vendidas por região: 
 [ 760 1500 4320 1790]

Produto mais vendido: Produto 5
Produto menos vendido: Produto 4
Região mais vendida: Região 3
Região menos vendida: Região 1

Matriz de receitas por produto e região:
[[ 3588. 10166. 26611.  6279.]
 [ 3992.  7485. 27944. 14970.]
 [ 3980.  8358. 21890.  9552.]
 [ 4495.  8091. 28768. 16182.]
 [ 4619.  7450. 21605.  9238.]]

Receita total por região: [ 20674.  41550. 126818.  56221.]
