### Exercício 1 — Fácil: Criando e inspecionando matrizes

**Enunciado:** Crie as seguintes matrizes e exiba o `shape`, `ndim` e `size` de cada uma:

a) Uma matriz 3×3 com os valores de 1 a 9 (use `arange` + `reshape`).  
b) Uma matriz de zeros com 4 linhas e 2 colunas.  
c) A matriz identidade de tamanho 3.

In [14]:
import numpy as np

# Uma matriz 3x3 com valore de 1 a 9
matriz_3x3 = np.arange(1, 10)

print(matriz_3x3.reshape(3,3))
print("shape:", matriz_3x3.shape)
print("ndim:", matriz_3x3.ndim)
print("size:", matriz_3x3.size)
print()
# Uma matriz de zeros com 4 linhas e 2 colunas
matriz_zeros = np.zeros((4,2))
print(matriz_zeros)
print("shape:", matriz_zeros.shape)
print("ndim:", matriz_zeros.ndim)
print("size:", matriz_zeros.size)
print()

#A matriz identidade de tamanho 3
matriz_ident = np.eye(3)
print(matriz_ident)
print("shape:", matriz_ident.shape)
print("ndim:", matriz_ident.ndim)
print("size:", matriz_ident.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (9,)
ndim: 1
size: 9

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
shape: (4, 2)
ndim: 2
size: 8

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
shape: (3, 3)
ndim: 2
size: 9


### Exercício 3 — Médio: Reshape, flatten e estatísticas por eixo

**Enunciado:** Você tem as vendas mensais de uma loja ao longo de um ano, registradas em um array 1D de 12 elementos (Janeiro a Dezembro):

```python
vendas_ano = np.array([45, 52, 48, 60, 55, 70, 80, 78, 65, 58, 50, 90])
```

1. Reorganize esse array em uma matriz `(4, 3)` onde cada linha representa um trimestre e cada coluna representa um mês dentro do trimestre.
2. Calcule o total de vendas por trimestre (soma por linha — `axis=1`).
3. Calcule a média de vendas por mês dentro de cada trimestre (já feito pelo item 2 se dividir por 3).
4. Identifique o trimestre com maior faturamento.
5. Use `flatten()` para recuperar o array original.

In [25]:
# 1. Reorganize esse array em uma matriz `(4, 3)` onde cada linha representa um trimestre e cada coluna representa 
# um mês dentro do trimestre.
vendas_ano = np.array([45, 52, 48, 60, 55, 70, 80, 78, 65, 58, 50, 90])
print(vendas_ano.reshape(4,3))
print()
# 2. Calcule o total de vendas por trimestre (soma por linha — `axis=1`).

# 3. Calcule a média de vendas por mês dentro de cada trimestre (já feito pelo item 2 se dividir por 3).

# 4. Identifique o trimestre com maior faturamento.

# 5. Use `flatten()` para recuperar o array original.
print(vendas_ano.flatten())

[[45 52 48]
 [60 55 70]
 [80 78 65]
 [58 50 90]]

[45 52 48 60 55 70 80 78 65 58 50 90]


### Exercício 2 — Fácil: Indexação e fatiamento

**Enunciado:** Dada a matriz de temperaturas diárias de 3 cidades ao longo de 5 dias:

```python
temperaturas = np.array([
    [32, 33, 31, 29, 35],   # Cidade A
    [28, 27, 30, 26, 29],   # Cidade B
    [22, 24, 21, 23, 25]    # Cidade C
])
```

Extraia:
- A temperatura da Cidade B no 3º dia (índice 2).
- Todas as temperaturas da Cidade C.
- As temperaturas de todas as cidades no último dia.
- A submatriz das cidades A e B nos primeiros 3 dias.


In [48]:
temperaturas = np.array([
    [32, 33, 31, 29, 35],   # Cidade A : temp1, temp2, temp3, temp4, temp5
    [28, 27, 30, 26, 29],   # Cidade B
    [22, 24, 21, 23, 25]    # Cidade C
])

# A temperatura da Cidade B no 3º dia (índice 2)
print(temperaturas[1, 2])
print()

# Todas as temperaturas da Cidade C
print(temperaturas[2, :])
print()
# As temperaturas de todas as cidades no último dia
print(temperaturas[:, -1])
print()
# A submatriz das cidades A e B nos primeiros 3 dias
submatriz_temp = temperaturas[0:2, 0:3]
print(submatriz_temp)

30

[22 24 21 23 25]

[35 29 25]

[[32 33 31]
 [28 27 30]]
