### Exercício 1 — Fácil: Criando e inspecionando matrizes

**Enunciado:** Crie as seguintes matrizes e exiba o `shape`, `ndim` e `size` de cada uma:

a) Uma matriz 3×3 com os valores de 1 a 9 (use `arange` + `reshape`).  
b) Uma matriz de zeros com 4 linhas e 2 colunas.  
c) A matriz identidade de tamanho 3.

In [14]:
import numpy as np

# Uma matriz 3x3 com valore de 1 a 9
matriz_3x3 = np.arange(1, 10)

print(matriz_3x3.reshape(3,3))
print("shape:", matriz_3x3.shape)
print("ndim:", matriz_3x3.ndim)
print("size:", matriz_3x3.size)
print()
# Uma matriz de zeros com 4 linhas e 2 colunas
matriz_zeros = np.zeros((4,2))
print(matriz_zeros)
print("shape:", matriz_zeros.shape)
print("ndim:", matriz_zeros.ndim)
print("size:", matriz_zeros.size)
print()

#A matriz identidade de tamanho 3
matriz_ident = np.eye(3)
print(matriz_ident)
print("shape:", matriz_ident.shape)
print("ndim:", matriz_ident.ndim)
print("size:", matriz_ident.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (9,)
ndim: 1
size: 9

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
shape: (4, 2)
ndim: 2
size: 8

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
shape: (3, 3)
ndim: 2
size: 9


### Exercício 3 — Médio: Reshape, flatten e estatísticas por eixo

**Enunciado:** Você tem as vendas mensais de uma loja ao longo de um ano, registradas em um array 1D de 12 elementos (Janeiro a Dezembro):

```python
vendas_ano = np.array([45, 52, 48, 60, 55, 70, 80, 78, 65, 58, 50, 90])
```

1. Reorganize esse array em uma matriz `(4, 3)` onde cada linha representa um trimestre e cada coluna representa um mês dentro do trimestre.
2. Calcule o total de vendas por trimestre (soma por linha — `axis=1`).
3. Calcule a média de vendas por mês dentro de cada trimestre (já feito pelo item 2 se dividir por 3).
4. Identifique o trimestre com maior faturamento.
5. Use `flatten()` para recuperar o array original.

In [25]:
# 1. Reorganize esse array em uma matriz `(4, 3)` onde cada linha representa um trimestre e cada coluna representa 
# um mês dentro do trimestre.
vendas_ano = np.array([45, 52, 48, 60, 55, 70, 80, 78, 65, 58, 50, 90])
print(vendas_ano.reshape(4,3))
print()
# 2. Calcule o total de vendas por trimestre (soma por linha — `axis=1`).

# 3. Calcule a média de vendas por mês dentro de cada trimestre (já feito pelo item 2 se dividir por 3).

# 4. Identifique o trimestre com maior faturamento.

# 5. Use `flatten()` para recuperar o array original.
print(vendas_ano.flatten())

[[45 52 48]
 [60 55 70]
 [80 78 65]
 [58 50 90]]

[45 52 48 60 55 70 80 78 65 58 50 90]


### Exercício 2 — Fácil: Indexação e fatiamento

**Enunciado:** Dada a matriz de temperaturas diárias de 3 cidades ao longo de 5 dias:

```python
temperaturas = np.array([
    [32, 33, 31, 29, 35],   # Cidade A
    [28, 27, 30, 26, 29],   # Cidade B
    [22, 24, 21, 23, 25]    # Cidade C
])
```

Extraia:
- A temperatura da Cidade B no 3º dia (índice 2).
- Todas as temperaturas da Cidade C.
- As temperaturas de todas as cidades no último dia.
- A submatriz das cidades A e B nos primeiros 3 dias.


In [48]:
temperaturas = np.array([
    [32, 33, 31, 29, 35],   # Cidade A : temp1, temp2, temp3, temp4, temp5
    [28, 27, 30, 26, 29],   # Cidade B
    [22, 24, 21, 23, 25]    # Cidade C
])

# A temperatura da Cidade B no 3º dia (índice 2)
print(temperaturas[1, 2])
print()

# Todas as temperaturas da Cidade C
print(temperaturas[2, :])
print()
# As temperaturas de todas as cidades no último dia
print(temperaturas[:, -1])
print()
# A submatriz das cidades A e B nos primeiros 3 dias
submatriz_temp = temperaturas[0:2, 0:3]
print(submatriz_temp)

30

[22 24 21 23 25]

[35 29 25]

[[32 33 31]
 [28 27 30]]


### Exercício 5 — Desafio: Mini Análise de Dataset com Matrizes

**Enunciado:** Uma empresa de e-commerce tem os dados de 5 produtos em 4 regiões do Brasil (Norte, Nordeste, Sudeste, Sul), representando as **quantidades vendidas** no mês:

```python
quantidades = np.array([
    [120, 340, 890, 210],   # Produto 1
    [ 80, 150, 560, 300],   # Produto 2
    [200, 420, 1100, 480],  # Produto 3
    [ 50,  90,  320, 180],  # Produto 4
    [310, 500, 1450, 620]   # Produto 5
])

precos = np.array([29.90, 49.90, 19.90, 89.90, 14.90])  # Preço de cada produto
```

Resolva **sem usar laços `for`**:

1. Calcule a receita total gerada por cada produto em todas as regiões (soma das colunas de cada linha × preço).
2. ''Calcule o total de unidades vendidas por região (soma de cada coluna).
3. Identifique qual produto e qual região têm o maior e o menor volume de vendas.
4. Crie uma matrix de receitas `(5, 4)` onde cada célula é `quantidade × preço_do_produto` para aquela região. *(Dica: use reshape ou broadcasting 2D.)*
5. Exiba a receita total por região.''

> 💡 **Dica para o item 4:** Tente `quantidades * precos.reshape(5, 1)` — isso multiplica cada linha pelo preço correspondente daquele produto (broadcasting 2D).


In [5]:
import numpy as np

quantidades = np.array([
    [120, 340, 890, 210],   # Produto 1
    [ 80, 150, 560, 300],   # Produto 2
    [200, 420, 1100, 480],  # Produto 3
    [ 50,  90,  320, 180],  # Produto 4
    [310, 500, 1450, 620]   # Produto 5
])

precos = np.array([29.90, 49.90, 19.90, 89.90, 14.90])  # Preço de cada produto

# Calcule a receita total gerada por cada produto em todas as regiões (soma das colunas de cada linha x preço)
receita_total = np.sum(quantidades, axis=1) * precos
print("Receita total por produto:", receita_total)
print()

# 2. Calcule o total de unidades vendidas por região (soma de cada coluna).
total_por_regiao = np.sum(quantidades, axis=0)
print("Total de unidades vendidas por região:", total_por_regiao)
print()

# 3. Identifique qual produto e qual região têm o maior e o menor volume de vendas.
produto_mais_vendido = np.argmax(np.sum(quantidades, axis=1))
produto_menos_vendido = np.argmin(np.sum(quantidades, axis=1))
regiao_mais_vendida = np.argmax(np.sum(quantidades, axis=0))
regiao_menos_vendida = np.argmin(np.sum(quantidades, axis=0))
print(f"Produto mais vendido: Produto {produto_mais_vendido + 1}")
print(f"Produto menos vendido: Produto {produto_menos_vendido + 1}")
print(f"Região mais vendida: Região {regiao_mais_vendida + 1}")
print(f"Região menos vendida: Região {regiao_menos_vendida + 1}")
print()

# 4. Crie uma matrix de receitas `(5, 4)` onde cada célula é `quantidade × preço_do_produto` para aquela região. 
# #*(Dica: use reshape ou broadcasting 2D.)*
precos = precos.reshape(5,1)
receitas = quantidades * precos
print("Matriz de receitas por produto e região:")
print(receitas)
print()

# 5. Exiba a receita total por região.
receita_por_regiao = np.sum(receitas, axis=0)
print("Receita total por região:", receita_por_regiao)  

Receita total por produto: [46644. 54391. 43780. 57536. 42912.]

Total de unidades vendidas por região: [ 760 1500 4320 1790]

Produto mais vendido: Produto 5
Produto menos vendido: Produto 4
Região mais vendida: Região 3
Região menos vendida: Região 1

Matriz de receitas por produto e região:
[[ 3588. 10166. 26611.  6279.]
 [ 3992.  7485. 27944. 14970.]
 [ 3980.  8358. 21890.  9552.]
 [ 4495.  8091. 28768. 16182.]
 [ 4619.  7450. 21605.  9238.]]

Receita total por região: [ 20674.  41550. 126818.  56221.]
