In [4]:
# Instalação

!pip install numpy

In [5]:
# Importação
import numpy as np

In [6]:
print(np.__version__)

2.4.4


In [9]:
# Criando um array
faturamento = np.array([1000, 1500, 2000, 2500, 3000])
print(faturamento)
print(type(faturamento))

[1000 1500 2000 2500 3000]
<class 'numpy.ndarray'>


In [16]:
# np.arange(inicio, fim, passo)

numeros = np.arange(0, 10, 2)
print(numeros)

[0 2 4 6 8]


In [22]:
# np.linspace(inicio, fim, quantidade)

numeros_linspace = np.linspace(0, 10, 5)
print(numeros_linspace)

[ 0.   2.5  5.   7.5 10. ]


In [25]:
# np.zeros(tamanho), np.ones(tamanho), np.full(tamanho, valor)

zeros = np.zeros(5)
print(zeros)

ones = np.ones(5)
print(ones)

full = np.full(5, 7)
print(full)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[7 7 7 7 7]


In [26]:
# Inspecionando atributos de um array

vendas = np.array([100, 200, 300, 400, 500])

print(vendas.shape)  # Dimensão do array
print(vendas.size)   # Número total de elementos
print(vendas.dtype)  # Tipo de dados dos elementos
print(vendas.ndim)   # Número de dimensões

(5,)
5
int64
1


In [28]:
# Indexação e slicing

notas = np.array([7.5, 8.0, 6.5, 9.0, 5.5])
print(notas[0])   # Acessa o primeiro elemento
print(notas[-1])  # Acessa o último elemento
print(notas[1:4]) # Acessa os elementos do índice 1 ao 3

7.5
5.5
[8.  6.5 9. ]


In [32]:
# Element-wise e Broadcasting

salarios = np.array([3000, 4000, 5000, 6000])

# Broadcasting: multiplicar cada salário por 1.1 (aumento de 10%)
salarios_aumentados = salarios * 1.1
print(salarios_aumentados)

# Element-wise: somar um array de bônus a cada salário
bonus = np.array([500, 600, 700, 800])
salarios_com_bonus = salarios + bonus
print(salarios_com_bonus)

[3300. 4400. 5500. 6600.]
[3500 4600 5700 6800]


In [39]:
# Funções Matemáticas e Estatísticas
faturamento_diario = np.array([1000, 1500, 2000, 2500, 3000])

# Total da semana
print(f"Total da semana: R$ {np.sum(faturamento_diario):,.2f}")
# media diária
print(f"Média diária: R$ {np.mean(faturamento_diario):,.2f}")
# Desvio padrão da semana
print(f"Desvio padrão: R$ {np.std(faturamento_diario):,.2f}")
# Pior dia
print(f"Pior dia: R$ {np.min(faturamento_diario):,.2f}")
# Melhor dia
print(f"Melhor dia: R$ {np.max(faturamento_diario):,.2f}")

print(f"Índice do melhor dia: {np.argmax(faturamento_diario)}")
print(f"Índice do pior dia: {np.argmin(faturamento_diario)}")

Total da semana: R$ 10,000.00
Média diária: R$ 2,000.00
Desvio padrão: R$ 707.11
Pior dia: R$ 1,000.00
Melhor dia: R$ 3,000.00
Índice do melhor dia: 4
Índice do pior dia: 0


### Exercício 1 — Fácil: Criando e inspecionando arrays

**Enunciado:** Você recebeu as temperaturas máximas (em °C) de uma cidade durante uma semana: `[32, 28, 35, 31, 29, 33, 36]`. Crie um array NumPy com esses valores e exiba: o array completo, seu `shape`, `dtype`, `ndim` e `size`.

In [ ]:
# Criando o array
temperaturas = np.array([32, 28, 35, 31, 29, 33, 36])

# Atributos do array dentro do print

print(f"Array completo: {temperaturas}")
print(f"Dimensão: {temperaturas.shape}")
print(f"Tipo: {temperaturas.dtype}")
print(f"Número de dimensões: {temperaturas.ndim}")
print(f"Tamanho: {temperaturas.size}")

Array completo: [32 28 35 31 29 33 36]
Dimensão: (7,)
Tipo: int64
Número de dimensões: 1
Tamanho: 7


In [45]:
# Criando o array
temperaturas = np.array([32, 28, 35, 31, 29, 33, 36])

# Atributos
dimensao = temperaturas.shape
tipo = temperaturas.dtype
numero_dimensoes = temperaturas.ndim
tamanho = temperaturas.size

print(f"Array completo: {temperaturas}")
print(f"Dimensão: {dimensao}")
print(f"Tipo: {tipo}")
print(f"Número de dimensões: {numero_dimensoes}")
print(f"Tamanho: {tamanho}")

Array completo: [32 28 35 31 29 33 36]
Dimensão: (7,)
Tipo: int64
Número de dimensões: 1
Tamanho: 7


### Exercício 2 — Fácil: Indexação e slicing

**Enunciado:** Usando o array de temperaturas do exercício anterior `[32, 28, 35, 31, 29, 33, 36]`, extraia:
- A temperatura de quinta-feira (5º dia da semana)
- A temperatura do último dia
- As temperaturas do meio da semana (terça, quarta e quinta — índices 1, 2 e 3)

In [57]:
# Temperatura de quinta-feira (Considerando que a semana começa na segunda-feira)
print(f"Temperatura de quinta-feira: {temperaturas[3]}°C")
# Se começar no domingo, quinta-feira seria o índice 4
print(f"Temperatura de quinta-feira (semana começando no domingo): {temperaturas[4]}°C")

# Temperatura do último dia
print(f"Temperatura do último dia: {temperaturas[-1]}°C")

# Temperaturas do meio da semana
print(f"Temperaturas do meio da semana: {temperaturas[1:4]}")

Temperatura de quinta-feira: 31°C
Temperatura de quinta-feira (semana começando no domingo): 29°C
Temperatura do último dia: 36°C
Temperaturas do meio da semana: [28 35 31]


### Exercício 3 — Médio: Operações e funções estatísticas

**Enunciado:** Uma padaria registrou suas vendas (em R$) de segunda a sábado: `[450.00, 320.50, 510.75, 489.00, 605.25, 780.50]`. Com esse array:

1. Calcule o total faturado na semana.
2. Calcule a média diária de vendas.
3. Identifique o menor e o maior faturamento.
4. Aplique um desconto de 5% em todos os dias (simule uma promoção onde a padaria deu 5% de cashback). Exiba os valores após o desconto.

In [62]:
# Criando o array de vendas de segunda a sábado
vendas = np.array([450.00, 320.50, 510.75, 489.00, 605.25, 780.50])
print(f"Vendas da semana: {vendas}")

# 1. Calcule o total de vendas da semana
total_vendas = np.sum(vendas)
print(f"Total de vendas da semana: R$ {total_vendas:.2f}")

# 2. Calcule a média diária de vendas
media_vendas = np.mean(vendas)
print(f"Média diária de vendas: R$ {media_vendas:.2f}")

# 3. Identifique o menor e o maior faturamento
min_vendas = np.min(vendas)
max_vendas = np.max(vendas)
print(f"O menor faturamento foi: R$ {min_vendas:.2f}")
print(f"O maior faturamento foi: R$ {max_vendas:.2f}")

# 4. Aplique um desconto de 5% em todos os dias (simule uma promoção onde a padaria deu 5% de cashback).
# Exiba os valores após o desconto.
vendas_com_desconto = vendas * 0.95
print(f"Vendas após o desconto de 5%: R$ {vendas_com_desconto.round(2)}")

Vendas da semana: [450.   320.5  510.75 489.   605.25 780.5 ]
Total de vendas da semana: R$ 3156.00
Média diária de vendas: R$ 526.00
O menor faturamento foi: R$ 320.50
O maior faturamento foi: R$ 780.50
Vendas após o desconto de 5%: R$ [427.5  304.47 485.21 464.55 574.99 741.47]


### Exercício 4 — Médio: Arange e Linspace

**Enunciado:**

a) Use `np.arange()` para criar um array com todos os números pares de 0 a 20 (inclusive).  
b) Use `np.linspace()` para criar um array com exatamente 7 valores igualmente espaçados entre 0% e 100% (representando faixas de desconto de uma promoção progressiva).  
c) Exiba ambos os arrays e seus respectivos `shape`.


In [67]:
# a) Use np.arange para criar um array com todos os números pares de 0 a 20 (inclusive).
numeros_pares = np.arange(0, 21, 2)

# b) use np.linspace() para criar um array com exatamente 7 valores igualmente espaçados entre 0% e 100%
# (representando faixas de desconto de uma promoção progressiva)
descontos = np.linspace(0, 100, 7)

# c) Exiba ambos os arrays e seus respectivos shape.
print(f"Números pares de 0 a 20: {numeros_pares}")
print(f"Shape dos números pares: {numeros_pares.shape}")
print(f"Faixas de desconto (em %): {descontos}")
print(f"Shape das faixas de desconto: {descontos.shape}")

Números pares de 0 a 20: [ 0  2  4  6  8 10 12 14 16 18 20]
Shape dos números pares: (11,)
Faixas de desconto (em %): [  0.          16.66666667  33.33333333  50.          66.66666667
  83.33333333 100.        ]
Shape das faixas de desconto: (7,)


### Exercício 5 — Desafio: Análise comparativa com arrays

**Enunciado:** Duas equipes de vendas registraram seus resultados mensais ao longo de 6 meses:

- **Equipe A:** `[42000, 38500, 51000, 47300, 55800, 49200]`
- **Equipe B:** `[39000, 41200, 48700, 52000, 44600, 53100]`

Resolva as seguintes questões **sem usar laços `for`** (use apenas operações NumPy):

1. Qual equipe teve o maior faturamento **total** em 6 meses?
2. Calcule a diferença de vendas mês a mês (Equipe A − Equipe B). Em quais meses a Equipe A superou a Equipe B?
3. Calcule a média de cada equipe e o desvio padrão. Qual equipe é mais consistente (menor desvio)?
4. Crie um array `bonus` onde cada equipe recebe 8% do seu próprio faturamento mensal como bônus. Exiba o total de bônus de cada equipe.

In [99]:
Equipe_A = np.array([42000, 38500, 51000, 47300, 55800, 49200])
Equipe_B = np.array([39000, 41200, 48700, 52000, 44600, 53100])

# 1. Qual equipe teve o maior faturamento total em 6 meses?
total_equipe_a = np.sum(Equipe_A)
total_equipe_b = np.sum(Equipe_B)
if total_equipe_a > total_equipe_b:
    print(f"A Equipe A teve o maior faturamento total: R$ {total_equipe_a:,.2f}")
else:
    print(f"A Equipe B teve o maior faturamento total: R$ {total_equipe_b:,.2f}")
print()
# 2. Calcule a diferença de vendas mês a mês (Equipe A - Equipe B). Em quais meses a Equipe A superou a Equipe B?
diferenca_mensal = Equipe_A - Equipe_B
print(f"Diferença de vendas mês a mês (Equipe A - Equipe B): {diferenca_mensal}")
meses_a_supera_b = diferenca_mensal > 0
'print(f"Meses em que a Equipe A superou a Equipe B: {meses_a_supera_b}")'
print(f"Meses em que a Equipe A superou a Equipe B (índices): {np.where(meses_a_supera_b)[0]}")
print()
# 3. Calcule a média de cada equipe e o desvio padrão. Qual equipe é mais consistente (menor desvio)?
media_a = np.mean(Equipe_A)
desvio_a = np.std(Equipe_A)
print(f" Média Equipe A: {media_a:,.2f}, Desvio Padrão A: {desvio_a:,.2f}")
media_b = np.mean(Equipe_B)
desvio_b = np.std(Equipe_B)
print(f" Média Equipe B: {media_b:,.2f}, Desvio Padrão B: {desvio_b:,.2f}")
if desvio_a < desvio_b:
    print("A Equipe A é mais consistente.")
elif desvio_b < desvio_a:
    print("A Equipe B é mais consistente.")
else:
    print("Ambas as equipes têm o mesmo desvio padrão, portanto são igualmente consistentes.")
print()
# 4. Crie um array `bonus` onde cada equipe recebe 8% do seu próprio faturamento mensal como bônus. 
# Exiba o total de bônus de cada equipe.
bonus_a = Equipe_A * 0.08
bonus_b = Equipe_B * 0.08
total_bonus_a = np.sum(bonus_a)
total_bonus_b = np.sum(bonus_b)
print(f"Total de bônus da Equipe A: R$ {total_bonus_a:,.2f}")
print(f"Total de bônus da Equipe B: R$ {total_bonus_b:,.2f}")


A Equipe A teve o maior faturamento total: R$ 283,800.00

Diferença de vendas mês a mês (Equipe A - Equipe B): [ 3000 -2700  2300 -4700 11200 -3900]
Meses em que a Equipe A superou a Equipe B (índices): [0 2 4]

 Média Equipe A: 47,300.00, Desvio Padrão A: 5,702.05
 Média Equipe B: 46,433.33, Desvio Padrão B: 5,268.99
A Equipe B é mais consistente.

Total de bônus da Equipe A: R$ 22,704.00
Total de bônus da Equipe B: R$ 22,288.00


In [82]:
# 1. Sem usar o if...else
total_equipe_a = np.sum(Equipe_A)
total_equipe_b = np.sum(Equipe_B)
print(f"O faturamento da Equipe A: R$ {total_equipe_a:,.2f}")
print(f"O faturamento da Equipe B: R$ {total_equipe_b:,.2f}")
print("A equipe com maior faturamento total é a Equipe A")

O faturamento da Equipe A: R$ 283,800.00
O faturamento da Equipe B: R$ 278,600.00
A equipe com maior faturamento total é a Equipe A
